### ISSUE TITLE
Not possible to change qty or Batch Id for selected item from POS

### ISSUE THREAD

**Issue by mdwala** [frappe/erpnext#11003]
**In reference to [https://discuss.erpnext.com/t/pos-change-selected-batch/28884](url)** 

**Not possible to change qty or Batch Id for selected item from POS**
**See steps:**

1. Selected Batches
![1](https://user-images.githubusercontent.com/24455908/31053749-7b5abbba-a6b5-11e7-818e-16b35c20e4fa.png)

2. Item added after selecting batches
![2](https://user-images.githubusercontent.com/24455908/31053754-8cc6ec02-a6b5-11e7-8ae3-7c592ebc1dbe.png)

3. But not possible to change/edit batches or quantity. Clicking on + - qty bring this screen comes where already selected batch not showing
![3](https://user-images.githubusercontent.com/24455908/31053760-a1ec04f0-a6b5-11e7-9be7-3e758a0f6263.png)

**Comment by rohitwaghchaure** [comment]
Hi @mdwala 

We have fixed this issue can you please check and confirm the issue has resolved

**Comment by mdwala** [comment]
Hi @rohitwaghchaure 
Still facing issue for selecting batch.

1)Selecting two batches, adds only 1st batch quantity.
![1](https://user-images.githubusercontent.com/24455908/31163062-a7fbaaa6-a8f1-11e7-84dd-5d9045cb4b7b.png)
![2](https://user-images.githubusercontent.com/24455908/31163063-a7ff561a-a8f1-11e7-80a1-d247afc28cb5.png)

2) Clicking on + or -, batch selection screen only shows 1st batch without available quantity.
![3](https://user-images.githubusercontent.com/24455908/31163091-c44e4cae-a8f1-11e7-87bc-8d456c333cc3.png)

**Comment by tundebabzy** [comment]
Fixed in #11767 and #11768 . Do note that #11767 was merged into develop so will take a couple of days before it goes live
