### ISSUE TITLE
Error when trying to change desktop icons

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#11670]
Uncaught SyntaxError: Unexpected identifier
    at Object._eval [as eval] (desk.min.js?ver=1511227504.0:508)
    at Class.init (desk.min.js?ver=1511227504.0:9644)
    at new Class (desk.min.js?ver=1511227504.0:37)
    at desk.min.js?ver=1511227504.0:9615
    at Object.with_page (desk.min.js?ver=1511227504.0:9591)
    at desk.min.js?ver=1511227504.0:9611
    at Object.with_doctype (desk.min.js?ver=1511227504.0:5478)
    at Object.show (desk.min.js?ver=1511227504.0:9610)
    at Object.frappe.route (desk.min.js?ver=1511227504.0:2183)
    at desk.min.js?ver=1511227504.0:2298

I get this error when trying to load the "Change desktop icons" page....

And weirdly... since last update all desktop icons has reset...

Thanks,

G.

**Comment by rohitwaghchaure** [comment]
@gbard 
Can you please share the name of language you're using in your account?

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/frappe/pull/4518

**Comment by gbard** [comment]
I'm using "fr" but even after switching to "en" the issue persist.

**Comment by rohitwaghchaure** [comment]
@gbard 

We have fixed the issue and soon we'll release it
