### ISSUE TITLE
XSS on Login Page

### ISSUE THREAD

**Issue by kentbayron** [frappe/erpnext#11750]
Hello Team,
I found a Cross Site Scripting (XSS) Bug in the Login page.

Steps to Reproduce:
1. Install Frappe and after installation
2. Access the server for me im running (localhost:8000)  and Go to Login Page
3. Insert this malicious script "><script>alert(document.cookie)</script> to user field
4. and the XSS will trigger.

Remedy:
In general, spending time on input validation and output sanitization and escaping will make your application safe.

![xss2](https://user-images.githubusercontent.com/16931096/33297723-926b28e0-d41d-11e7-8b71-4b1ec041e7c4.png)
![xss](https://user-images.githubusercontent.com/16931096/33297724-92af7b4e-d41d-11e7-90e9-eb35be04149b.png)

**Comment by felixvarghese** [comment]
pinging @revant and @saurabh6790

**Comment by revant** [comment]
I'm not able to replicate this.
Username `"><script>alert(document.cookie)</script>` ? with " at the beginning?

**Comment by felixvarghese** [comment]
It's replicable for me on the demo instance
![image](https://user-images.githubusercontent.com/3396162/33331863-c60f052a-d488-11e7-8eba-8c4f48dc1683.png)

**Comment by revant** [comment]
Yes I can replicate it on demo. 

Tried this in console
```
var args = {};
args.cmd = "login";
args.usr = "\"><script>console.log(1)</script>";
args.pwd = "123";
args.device = "desktop";
login.call(args);
```

on demo.erpnext.com/api/method/version (9.2.15) 
![screenshot from 2017-11-28 22-31-06](https://user-images.githubusercontent.com/1040161/33333074-f2204518-d48b-11e7-82db-0201c2f4530b.png)

@saurabh6790 I think it is related to configuration? I am not able to replicate it on foundation website.

**Comment by kentbayron** [comment]
Hello There,

I can replicate it on the demo. No, is not related to the configuration,
its in the handling user input without any validation you must validate the
user input before it goes to the server or try to escape dynamic content
example from " to &#32.
Let me know if there;s i can do.

Best Regards,
Kent Bayron

**Comment by system19** [comment]
Well spotted @kentbayron as this is a major security flaw. **All** text fields should be sanitised. Not just the login one. Thanks again @kentbayron

**Comment by felixvarghese** [comment]
This is not replicable on my instance (although it is an older ERPNext version). I did a quick google search for other instances, and only found one instance with this issue (out of 10). Most instances properly return an "Invalid Login" message.

**Comment by kentbayron** [comment]
Hello,
I just install latest erpnext version yesterday and also i test it on the
demo.erpnext.com earlier.
 and the bug is still there.

**Comment by kentbayron** [comment]
![screenshot from 2017-11-29 13-52-21](https://user-images.githubusercontent.com/16931096/33360054-f09bdd02-d50c-11e7-9590-47f4621730fd.png)

Installed Apps
ERPNext: v9.x.x-develop (a14baf4) (develop)
Frappe Framework: v9.x.x-develop (4c42ff2) (develop)

**Comment by achillesrasquinha** [comment]
So, this has been fixed for Login as of now. The problem is as follows:
1. `frappe.call` stringifies arguments (All good).
2. `frappe.throw` (depends on `frappe.msgprint`), sends back non-sanitised strings. This causes the client side to accept the message as a string which appends to the DOM HTML (Check of `frappe.msgprint Client in `web.js`).

My take, this is more than a simple fix.
1. Any server-side strings must be sanitized via `jinja2.escape` (already a dependency). Let's figure out where exactly this is needed.
2. The receiver end on the client-side must attach safe sanitised messages received at the other end. This is because, for many cases the body receives direct "unsafe" strings that directly get attached to the DOM (and thereby triggers the same).

**Comment by kentbayron** [comment]
Hello,
I can confirm that its fix now, i already test it in my machine and the script is not popping anymore.

Regards,
Kent

**Comment by kentbayron** [comment]
Hello Team,
I tested again the login page but it seems the XSS bug is still there, i can alert a pop up box. 
You may take a a look. 
![screenshot from 2017-12-15 10-45-34](https://user-images.githubusercontent.com/16931096/34024478-480e707a-e185-11e7-8f5b-923cefedb635.png)
![screenshot from 2017-12-15 10-45-18](https://user-images.githubusercontent.com/16931096/34024479-4857ce6e-e185-11e7-82df-8d0cbcee6d55.png)

**Comment by achillesrasquinha** [comment]
Hi, the fix was recently patched 2 days ago. Can you confirm on the latest develop branch? You seem to be on a branch that's 10 days old.

**Comment by achillesrasquinha** [comment]
If fixed, please close the issue. Thanks!

**Comment by tundebabzy** [comment]
Please reopen if issue still persists

**Comment by kentbayron** [comment]
Hi! Awesome, its already fixed! 
Regards, 
Kent Bayron
