### ISSUE TITLE
Value Rounding to 2 even when Precision is 3

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11856]
Value 1.990 gets rounded to 1.99... user has enabled precision upto three decimal places.

Example.

Sales Invoice has total of 1.990, but value gets rounded to 1.99, hence customer also makes lesser payment. A direct impact on the income received which is less than the receivable amount.

**Comment by achillesrasquinha** [comment]
Resolved [4578](https://github.com/frappe/frappe/issues/4578)

**Comment by mayamihaylova** [comment]
In v.11 in Cloud Round function still doesn't work properly with precision more than 2. Currency values are rounding to 2 even though precision is 6 for all prices like 0.001930, with 0 for the last digit after decimal point.
