### ISSUE TITLE
Bugs in charts.erpnext.com

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13126]
Reported by user via Support Issue /WN-SUP31248

- edit the chart of accounts: nothing happens when we click on the button start or fork.
- download chart of accounts: nothing happens when you click on download.
- create a new chart of accounts: nothing happens when you click on create a new chart of accounts

**Comment by barhamed** [comment]
yes we wait until the problem is solved

**Comment by barhamed** [comment]
@umairsy 
is there any news about the bug fix?

**Comment by barhamed** [comment]
now the page has an error message
![sans titre](https://user-images.githubusercontent.com/23336631/37269872-b720a63c-25cc-11e8-9c4c-7e0057ac7895.png)

**Comment by krnkris** [comment]
Now it works.

**Comment by barhamed** [comment]
yes it works,
and yes the buttons dont !!!!

**Comment by barhamed** [comment]
@umairsy @rmehta @nabinhait No one can fix this issue

**Comment by rmehta** [comment]
@barhamed @krnkris sorry for the delay. Fixed.

**Comment by barhamed** [comment]
@rmehta the "download" and the "create a new chart" btn not fixed yet

**Comment by krnkris** [comment]
Fork seem to fork only a kind of "base chart" instead what you want to choose.

**Comment by barhamed** [comment]
@krnkris but the download and the create a new chart btn don't work yet

**Comment by krnkris** [comment]
@barhamed has true words:
"download" and the "create a new chart" btn not fixed yet
+
Fork seem to fork only a kind of "base chart" instead what you want to choose.
Unfortunately not fixed jet.

**Comment by rmehta** [comment]
Fixed now.

**Comment by barhamed** [comment]
@rmehta thinks the create a new chart is fixed, but the download btn isn't
![sans titre](https://user-images.githubusercontent.com/23336631/37639743-e135c4e2-2c12-11e8-885d-18d925a60ff6.png)

**Comment by krnkris** [comment]
@barhamed has true words:
"download" btn not fixed yet
+
Fork seem to fork only a kind of "base chart" instead what you choose.
Unfortunately not fixed jet.

**Comment by barhamed** [comment]
@rmehta @umairsy @nabinhait the download btn don't work please can you fix it

**Comment by krnkris** [comment]
The fork is works, but somehow fork a base chart instead what shows on the display.

**Comment by barhamed** [comment]
@rmehta @umairsy @nabinhait the dowload btn steal don't work, please fix it

**Comment by xyeison** [comment]
I have the same problem :(

**Comment by achillesrasquinha** [comment]
Looking into! Looks like there's yet another bytes issue with download the tar.gzip

**Comment by achillesrasquinha** [comment]
Hi, can you now confirm on this please?

**Comment by krnkris** [comment]
@achillesrasquinha 
Confirm the download button works

**Comment by krnkris** [comment]
Fork seem to fork only a kind of "base chart" instead what you choose.
Unfortunately not fixed jet.

**Comment by krnkris** [comment]
There is way to delete from the user's forks, 
because each time I fork a new chart of account then it fills up with a new name, but
not possible to delete it at all.

**Comment by achillesrasquinha** [comment]
@krnkris - Can you please elaborate the steps?

**Comment by krnkris** [comment]
1. LOGIN
2. Choose this chart of account:
https://charts.erpnext.com/chart?company=Hungary%20-%20Chart%20of%20Accounts&forked=1&submitted=1

3.get this:
![kepernyokep 2018-03-25 20-56-34](https://user-images.githubusercontent.com/7963250/37878884-42b03d56-305f-11e8-8a76-a32ad8071ebf.png)

4. Try to Edit, Rename, Add child in rows ; +Add Root Account, but it is not works as should be:
![kepernyokep 2018-03-25 20-57-24](https://user-images.githubusercontent.com/7963250/37878889-4d3f5c98-305f-11e8-80c2-c7f13e38e5e3.png)

**Comment by achillesrasquinha** [comment]
Oh I get it!

@netchampfaris - There's `charts.js` that isn't compatible with the new build tool.

**Comment by krnkris** [comment]
In this case could you upload a new base chart of account with numbers.
From this I would made a new chart of account to my country.
Is it workable?

**Comment by barhamed** [comment]
the download btn create a popup window, so if you had block the popup window they dont show you the download item :)

**Comment by nabinhait** [comment]
> In this case could you upload a new base chart of account with numbers?

Account Number is still not supported in this portal. You have to include the numbers as a part of account name.

**Comment by achillesrasquinha** [comment]
Fixes getting Better. Could you please point out on the bottlenecks now?

**Comment by krnkris** [comment]
WOW 
Just works.
OK now seem ready to accept new chart of account with numbers.
Thank you!

**Comment by krnkris** [comment]
How we should put the numbering in to the account name?
Is it with example:
111.
or
111-
or
111 - 

Please explain.

**Comment by xyeison** [comment]
Hi, I am trying to create a child account but give me this error:

**"Root Type is mandatory"**

Thanks in advance!

**Comment by krnkris** [comment]
Why don't you choose a root type then?
It is a scroll down menu.

**Comment by krnkris** [comment]
@xyeison

Yes you right!
As before mentioned
“Account Number is still not supported in this portal. You have to include the numbers as a part of account name.”

Therefore please do not include the number in this way, because it is not accepted.

Try it without numbers.

I already asked how we should include the numbers, hopefully get an answer soon.

**Comment by xyeison** [comment]
@krnkris 

Keep giving me the same error without numbers, look:
Step 1
![image](https://user-images.githubusercontent.com/37752648/37933591-50878e54-3111-11e8-8872-1c4c310a35a3.png)

Step 2
![image](https://user-images.githubusercontent.com/37752648/37933613-5e212fc0-3111-11e8-993b-4e925decc367.png)

Step 3
![image](https://user-images.githubusercontent.com/37752648/37933647-6c9b5bac-3111-11e8-84a2-21cadae80b97.png)

Error Message:
![image](https://user-images.githubusercontent.com/37752648/37933665-79777c7a-3111-11e8-97d3-d55cd9bf5e0c.png)

If I select a account type, give me the same error
![image](https://user-images.githubusercontent.com/37752648/37933685-90241be0-3111-11e8-94a2-31a68a600446.png)

**Comment by krnkris** [comment]
@xyeison 

No clue, for me it works:

![kepernyokep 2018-03-27 08-20-24](https://user-images.githubusercontent.com/7963250/37950166-de940534-3197-11e8-95f9-f940e58d33e0.png)

![kepernyokep 2018-03-27 08-20-55](https://user-images.githubusercontent.com/7963250/37950178-e5356ed2-3197-11e8-8628-54e1a9669099.png)

**Comment by krnkris** [comment]
@xyeison 

OK. The bottleneck is the:
Add Child

@achillesrasquinha   
Please correct thi, because without it we cant create new charts.
