### ISSUE TITLE
Non Profit Member should not have email mandatory

### ISSUE THREAD

**Issue by kothagunda** [frappe/erpnext#13205]
Since farmers in a COOP dont have email, can the email field in the Non Profit Member be made non mandatory. 

Similarly membership type, can that also be made non-mandatory ? There might not be any memership types at all, and no membership fee. So having membership type should not be mandatory.

![image](https://user-images.githubusercontent.com/30433779/37076442-9fef0a7c-21fc-11e8-9e24-175a308da864.png)

Related to https://github.com/frappe/erpnext/issues/13110

**Comment by umairsy** [comment]
It has been fixed and merged into develop branch. It means it will be released with version 11.

@saurabh6790  @nabinhait  can we cherrypick into hotfix branch? They have already started implementing ERPNext at FPOs.

**Comment by kothagunda** [comment]
Great thank you very much @umairsy

**Comment by kothagunda** [comment]
Hi @umairsy  (cc @saurabh6790 @nabinhait  )
I installed latest from develop branch today, but still see email, and membership type fields as mandatory. Just wondering if this was pulled into develop.


![image](https://user-images.githubusercontent.com/30433779/37902324-ba32b46e-3111-11e8-8498-ba1b39e6adc4.png)


Installed Apps
ERPNext: v11.x.x-develop (061d912) (develop)
Frappe Framework: v11.x.x-develop (20052f0) (develop)

GIT Information

root@fpo-developer-mode:~# cd /home/frappe/frappe-bench/apps/erpnext/

root@fpo-developer-mode:/home/frappe/frappe-bench/apps/erpnext# git log
commit 061d912
Author: Nabin Hait nabinhait@gmail.com
Date: Fri Mar 23 16:20:27 2018 +0530

Fixed merge conflict

root@fpo-developer-mode:/home/frappe/frappe-bench/apps/erpnext# git remote -v
upstream https://github.com/frappe/erpnext (fetch)
upstream https://github.com/frappe/erpnext (push)

root@fpo-developer-mode:/home/frappe/frappe-bench/apps/erpnext# git branch

    develop

root@fpo-developer-mode:/home/frappe/frappe-bench/apps/erpnext#

**Comment by Olawale1** [comment]
Hi ,

I was just about to open an issue for this! As at last I checked, it hadn't been fixed

@umairsy should I open a new issue for this? It's actually a very important point

Thanks

**Comment by zefanja** [comment]
This is also a problem for (young) Students in the Education domain.
