### ISSUE TITLE
[V11] Errors after enabling 2 factor authentication

### ISSUE THREAD

**Issue by wispmac** [frappe/erpnext#14445]
Our version:
ERPNext: v11.0.3-beta.13 () (develop)
Frappe Framework: v11.0.3-beta.12 () (develop)

After enabling 2 factor authentication, we keep getting the following error in logs:

{'retry': 0, 'log': <function log at 0x7f42aeac5140>, 'site': u'el.cyahi.com', 'event': u'all', 'method_name': u'frappe.twofactor.delete_all_barcodes_for_users', 'method': <function delete_all_barcodes_for_users at 0x7f42aea8f668>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'frappe.twofactor.delete_all_barcodes_for_users'}
Traceback (most recent call last):
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/background_jobs.py", line 97, in execute_job
    method(**kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/twofactor.py", line 376, in delete_all_barcodes_for_users
    if not two_factor_is_enabled():
  File "/opt/bench/erpnext/apps/frappe/frappe/twofactor.py", line 32, in two_factor_is_enabled
    user_doc = frappe.get_doc("User", user)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 641, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 69, in get_doc
    return controller(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 104, in __init__
    self.load_from_db()
  File "/opt/bench/erpnext/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 327, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 313, in msgprint
    _raise_exception()
  File "/opt/bench/erpnext/apps/frappe/frappe/__init__.py", line 286, in _raise_exception
    raise raise_exception(msg)
DoesNotExistError: User None not found

**Comment by wispmac** [comment]
Still facing the issue

**Comment by jaichavan** [comment]
Hello, @wispmac 
Thanks for reporting the issue. Has it been resolved with the latest update?

**Comment by wispmac** [comment]
Sorry for the late reply. Yes. Its working fine now with the latest update.

**Comment by NUWebStudio** [comment]
Hi,
Im running 11.1.4 and Im having this issue every day logining into over 200+ errors from frappe.twofactor.delete_all_barcodes_for_users what version is this fixed in?

**Comment by SherifMalek** [comment]
Hello,
We are running v11.1.15, and we are still having this issue. More than 99+ errors from frappe.twofactor.delete_all_barcodes_for_users.

Any ideas how to fix this error?

**Comment by wispmac** [comment]
For the time being, till it is fixed by the developers, we have commented out the line "frappe.twofactor.delete_all_barcodes_for_users" from apps/frappe/frappe/hooks.py
