### ISSUE TITLE
Query reports not allowed for hosted users: a suggested solution

### ISSUE THREAD

**Issue by julsmon** [frappe/erpnext#16968]
Hosted users can't create their own query reports and the report builder is limited in terms of adding conditions to the data being served.
If for some reasons it's impossible to allow hosted users to create query reports, please at least add the chance of duplicating and modifying existing query reports that come as default. The chance of removing unwanted columns and adding extra columns to those would be strategic in creating (or recreating in Erpnext) essential corporate reports.

**Comment by rmehta** [comment]
This is now fixed! https://github.com/frappe/frappe/pull/7225

**Comment by julsmon** [comment]
Hello @rmehta, thanks for the heads up. Actually, I don't think it's completely fixed: I have tried removing existing columns from a query report and I am still not allowed to do it. I also tried duplicating and renaming the report, but the error "Only the administrator can create query / script reports" is still there. Do you have any insights? Thank you.
