### ISSUE TITLE
Bad Table Format When changing the Language to Arabic

### ISSUE THREAD

**Issue by ibrasec** [frappe/erpnext#17467]
we are having issues when changing the language to Arabic,
We noticed that the Table Format in the **Reports** Section of the **Human Resources** is very Bad, when you drag the Row, the above Row is Dragged in a rate not similar to its below.
![Screenshot_2019-05-02 مصاريف المركبة](https://user-images.githubusercontent.com/7280184/57082516-29789100-6cf7-11e9-9b9c-95d272b25e98.png)

Also the Data that supposed to be shown through the **Analytic** section of the **Human Resources** is not there
The attached compressed Video below might describe the problem better
[Reports_bugs.mp4.zip](https://github.com/frappe/erpnext/files/3138427/Reports_bugs.mp4.zip)

**Comment by dufani1** [comment]
The same issue, we are the ERPNext hosting user and our version 11.1.23

**Comment by deepeshgarg007** [comment]
@dufani1 @ibrasec this issue is fixed in latest v11 via https://github.com/frappe/datatable/pull/64
Closing this issue

**Comment by ibrasec** [comment]
@deepeshgarg007 
It is found that the issue is still exsist on Firefox version but not on google chrom version
