### ISSUE TITLE
Quality Management - Issues

### ISSUE THREAD

**Issue by xickomesquita** [frappe/erpnext#18490]
@hrwX 
Hi, I'm new here, so, please be patience:

1) I can't see the <Edit/Add Child/Delete> button.
![image](https://user-images.githubusercontent.com/38265198/61916395-b3af4a80-af1e-11e9-9314-04f7000e3cc6.png)
When I change language, it appears:

![image](https://user-images.githubusercontent.com/38265198/61916425-d3467300-af1e-11e9-86b5-9489b42f3101.png)

2) With portuguese, I can try to add a Child, but I can't:
![image](https://user-images.githubusercontent.com/38265198/61916446-f709b900-af1e-11e9-9bc6-d2ddf85b6a1d.png)

![image](https://user-images.githubusercontent.com/38265198/61916455-fd983080-af1e-11e9-94a2-129bd7bcf34a.png)

3) Can't edit these fields:
![image](https://user-images.githubusercontent.com/38265198/61916490-23bdd080-af1f-11e9-9ed8-03918362ec22.png)

so, I can't edit/delete this procedure:
![image](https://user-images.githubusercontent.com/38265198/61916522-3cc68180-af1f-11e9-8853-f5457be84294.png)

Thanks!

**Comment by govindsmenokee** [comment]
Yeah the entire module is of no use because of this issue.

**Comment by hrwX** [comment]
I have fixed these issues in the following PRs
- #18595 
- #18596

**Comment by xickomesquita** [comment]
> I have fixed these issues in the following PRs
> 
> * #18595
> * #18596

Hi, 1,2,3 and 4 ok! Thanks!!

Just can't sort the tree, using the names of the folders... 

UPDATE: Still can't sort the folders:

![image](https://user-images.githubusercontent.com/38265198/62987182-ead59500-be14-11e9-950c-93d9919b51b3.png)
