### ISSUE TITLE
duplicate student name under guardian

### ISSUE THREAD

**Issue by Nofal-Mami** [frappe/erpnext#19194]
Hi,
I have observed below issue, please help.

![image](https://user-images.githubusercontent.com/35137381/65771960-f8837780-e141-11e9-9076-9c98e8c30ecc.png)

Thx
Nofal

**Comment by Nofal-Mami** [comment]
Installed Apps

ERPNext: v12.1.5 (version-12)

Frappe Framework: v12.0.15 (version-12)

**Comment by crescent28** [comment]
@Nofal-Mami The issue has been fixed

**Comment by landaverdelbo** [comment]
Hi, @Nofal-Mami  , @crescent28 ,  what about this issue? the student child table still show more than one student.....

![image](https://user-images.githubusercontent.com/9533344/84215511-130d3f00-aa8c-11ea-8570-0116a826ac7d.png)

The pull request fix.. #19309 is about duplicated Guardians.. but the image of @Nofal-Mami  and this above.. are about Duplicated Students.. one row come from Student Applicant.. and the second one.. is created on.. Student Enrollment.

Do you have some issues still about this?
