### ISSUE TITLE
Asset: Bulk Submit doesn't Work

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#19647]
Steps:

1. Created 10 asset in draft via Purchase Receipt
2. From the list view, trying to update "Available for use date", which updates Depreciation Start Date (JS). This doesn't work when updating Available for Use Date from List View

<img width="1206" alt="Screenshot 2019-11-21 at 4 34 39 PM" src="https://user-images.githubusercontent.com/910238/69332863-93e62400-0c7d-11ea-9762-e837afa680f1.png">

<img width="1208" alt="Screenshot 2019-11-21 at 4 38 26 PM" src="https://user-images.githubusercontent.com/910238/69332870-96487e00-0c7d-11ea-8894-11abd8817c8c.png">

**Comment by nextchamp-saqib** [comment]
fixed: https://github.com/frappe/erpnext/pull/19666

**Comment by Osalama1** [comment]
the problem still happen in ERPNext: v13.21.0
but i still can submit them one by one only
![image](https://user-images.githubusercontent.com/32139293/170468709-58e17932-34a8-4f76-a5af-6e4d9bfbd99f.png)
