### ISSUE TITLE
A field with the name 'auto_repeat' already exists in doctype Sales Order.

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#22398]
## Description of the issue
After upgrading I'm facing this error `A field with the name 'auto_repeat' already exists in doctype Sales Order.` when trying to customize the form. 

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.x.x-develop
frappe 12.x.x-develop
```

## Steps to reproduce the issue

1. Go to sales order list
2. Go to customize form

### Observed result
An error appears and no fields appear. 

### Expected result
The form opens

### Stacktrace / full error message

![image](https://user-images.githubusercontent.com/20220341/85371944-c1f45500-b539-11ea-8042-662601fb6629.png)

## Additional information

OS version / distribution, `ERPNext` install method, etc.

Ubuntu 16.04
EasyInstall

**Comment by kennethsequeira** [comment]
@ioweb-gr cloud not replicate this on the latest develop.

Can you make sure accidentally there aren't two fields named 'auto_repeat'?

**Comment by ioweb-gr** [comment]
I guess it happened during upgrades so it's going to be hard to replicate. The message says itself there are two fields named auto repeat but the issue is that the user can't do anything about it 

The customize form page doesn't open and this is a standard field so I have no way to delete it. The most important thing is that there is no way to handle the issue on user's side

**Comment by littlebunyip** [comment]
I have just received this message also.

I have a custom script running for doctype Sales Order that uses a custom field named total_cartons. I have recently set up auto-repats for some sales orders. I have also disabled some auto-repeats for other sales orders. I have a Material Request auto_repeat running fine and can still customise the Material Request doctype without error.

Here is the web consol output:

```
XHRPOSThttp://littlebunyip.local/api/method/runserverobj
[HTTP/1.1 417 EXPECTATION FAILED 269ms]

Traceback (most recent call last):
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/handler.py", line 69, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/__init__.py", line 1086, in call
    return fn(*args, **newargs)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/handler.py", line 97, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 43, in runserverobj
    r = doc.run_method(method)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 1112, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 1095, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 814, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/custom/doctype/customize_form/customize_form.py", line 131, in fetch_to_customize
    create_custom_field(self.doc_type, df)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 134, in create_custom_field
    custom_field.insert()
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 224, in insert
    self.run_method("before_insert")
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 1112, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 1095, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/model/document.py", line 814, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 39, in before_insert
    frappe.throw(_("A field with the name '{}' already exists in doctype {}.").format(self.fieldname, self.dt))
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/__init__.py", line 396, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/__init__.py", line 375, in msgprint
    _raise_exception()
  File "/home/spidyip/frappe-bench/apps/frappe/frappe/__init__.py", line 326, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: A field with the name 'auto_repeat' already exists in doctype Sales Order.
request.js:356:14
```
Custom script attched to Sales Order doctype:

```
frappe.ui.form.on('Sales Order', {
	 validate(frm) {
        if (frm.doc.shipping_rule == "Refrigerated Transport") {
            if (frm.doc.total_qty % 4 !== 0) {
                msgprint('Total Quantity of items must be divisable by 4');
                validated = false;
            } else {
                frm.set_value('total_cartons', frm.doc.total_qty / 4);
                }
        } else {
            frm.set_value('total_cartons', "n/a" );
        }
    }
});
```
I've checked the mariadb database for duplicate field and there are no duplicate fields called auto_repeat. there is howver a field with the name auto_repeat. I don't have the skill to find where the culprit is from the python traceback sorry.

ERPNext: v13.x.x-develop () (develop)
Frappe Framework: v13.x.x-develop () (develop)

**Comment by timcu** [comment]
I am also getting this error. Mine is a clean install not an upgrade.
`bench init --frappe-branch version-13-beta frappe-bench`
`bench get-app --branch version-13-beta-pre-release erpnext`

**Comment by smthakor1979** [comment]
I also faced same issue in sales invoice and purchase invoice
Installed Apps
ERPNext: v13.0.0-beta.5 (version-13-beta)
Frappe Framework: v13.0.0-beta.6 (version-13-beta)

![image](https://user-images.githubusercontent.com/66081909/99698064-5d243300-2ab6-11eb-94da-a6d292322e95.png)

**Comment by iamkhalidbashir** [comment]
The same issue installed a fresh erpnext develop branch today

**Comment by ioweb-gr** [comment]
I didn't bump into the error after updating today. I think it was solved.

**Comment by iamkhalidbashir** [comment]
yes I think too

**Comment by heyberting** [comment]
I am still getting this error while trying to migrate a db from v11

**Comment by LunarisX** [comment]
getting the same error while migrating db from v12 to v13.

**Comment by smthakor1979** [comment]
Thank you for contacting us.

  

We will get back to you shortly.



Leave this conversation: https://bestroadways.frappe.cloud/api/method/frappe.email.queue.unsubscribe?email=reply%2Bapyfi5njtifjqovngueke4f6wogmjevbnhhcmxdk2y%40reply.github.com&doctype=Lead&name=CRM-LEAD-2021-00228&_signature=6234dcf23e9c78a9bf64ce15fa5f416d

**Comment by Rakeshsivaji65** [comment]
Is this issue resolved? @heyberting @V-PATURKAR @ioweb-gr @121tech-dev

**Comment by Louiscampagna** [comment]
I have the same problem v14 trying to customize customer form
