### ISSUE TITLE
Unable to Cancel Any Document

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#24786]
We are unable to cancel any document such as Payment Entry, Journal Entry. Following error is displayed:
TypeError: object of type 'NoneType' has no len()

**Comment by ankush** [comment]
Open browser console and copy-paste full error log, or from Bench console window. 

https://balsamiq.com/support/faqs/browserconsole

**Comment by sumeetagra** [comment]
Traceback (most recent call last):
  File "/opt/erpnext/erpnext/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 872, in cancel
    self._cancel()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 862, in _cancel
    self.save()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 309, in _save
    self.run_before_save_methods()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 903, in run_before_save_methods
    self.run_method("before_cancel")
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/erpnext/erpnext/apps/erpnext/erpnext/controllers/accounts_controller.py", line 118, in before_cancel
    validate_einvoice_fields(self)
  File "/opt/erpnext/erpnext/apps/erpnext/erpnext/__init__.py", line 129, in caller
    return frappe.get_attr(regional_overrides[region][fn_name])(*args, **kwargs)
  File "/opt/erpnext/erpnext/apps/erpnext/erpnext/regional/india/e_invoice/utils.py", line 26, in validate_einvoice_fields
    no_taxes_applied = len(doc.get('taxes', [])) == 0
TypeError: object of type 'NoneType' has no len()

request.js:355 Traceback (most recent call last):
  File "/opt/erpnext/erpnext/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/__init__.py", line 1071, in call
    return fn(*args, **newargs)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/desk/form/save.py", line 37, in cancel
    doc.cancel()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 872, in cancel
    self._cancel()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 862, in _cancel
    self.save()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 309, in _save
    self.run_before_save_methods()
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 903, in run_before_save_methods
    self.run_method("before_cancel")
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/erpnext/erpnext/apps/erpnext/erpnext/controllers/accounts_controller.py", line 118, in before_cancel
    validate_einvoice_fields(self)
  File "/opt/erpnext/erpnext/apps/erpnext/erpnext/__init__.py", line 129, in caller
    return frappe.get_attr(regional_overrides[region][fn_name])(*args, **kwargs)
  File "/opt/erpnext/erpnext/apps/erpnext/erpnext/regional/india/e_invoice/utils.py", line 26, in validate_einvoice_fields
    no_taxes_applied = len(doc.get('taxes', [])) == 0
TypeError: object of type 'NoneType' has no len()

**Comment by ankush** [comment]
Thank you for full report. This is already fixed and should be part of next release.

refer #24616

**Comment by sumeetagra** [comment]
Thanks for the update, but the error is still there in the following versions:
ERPNext: v12.18.0 (version-12)

Frappe Framework: v12.15.0 (version-12)

**Comment by ankush** [comment]
It's backported to version 12 too. So it should get fixed with next v12 release.

If you want to fix it on your site faster you can cherry-pick this commit: https://github.com/frappe/erpnext/commit/edfbb5d3be9a15ba671c3d5c8cf5b3fc22b28e66
