### ISSUE TITLE
bug: Production Plan: does not combine common Work Order Items

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26801]
## Description of the issue
A feature was added to the Production Plan here #25478 to consolidate order lines for the same Item into a single string of Work Orders. However, each consolidated line is still treated completely separately when generating sub-item work orders. It is common/conceivable that items on a production plan share the same sub-component, which should also be combined together when creating the Work Orders.

## Context information (for bug reports)

**Output of `bench version`**
```
13.6
```

## Steps to reproduce the issue

1. Create a consolidated Production Plan with lines that share a sub-component, e.g. blue and red cars that have the same wheels
2. Create the Work Orders

### Observed result
Separate work orders for the wheels for the red cars and blue cars

### Expected result
One work order for all the wheels

**Comment by nzepa74** [comment]
test

**Comment by yadavyk** [comment]
Fixed with [28558](https://github.com/frappe/erpnext/pull/28558)

**Comment by ankush** [comment]
Not fixed yet, PR open: https://github.com/frappe/erpnext/pull/28939
