### ISSUE TITLE
Report View groups by name - ERPNext: v13.14.1 (version-13)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#28466]
This is very new in ERPNext: v13.14.1 (version-13)

If you have an invoice with three invoice item lines, and on the report you pick columns under Items (Sales Invoice Item)
The resulting report should display three rows, for the said invoice. Twas the case.
Since version v13.14.1 (version-13), it only displays one row, and the first item only.

**Invoice**
![image](https://user-images.githubusercontent.com/1822868/142638263-4101b2da-4901-4395-b117-641846325808.png)

**Columns picked**
![image](https://user-images.githubusercontent.com/1822868/142638348-fde44746-9c29-49c9-8e2c-371bd82e6432.png)

**Report displayed.**
![image](https://user-images.githubusercontent.com/1822868/142638547-45d8c76a-f0a6-4d1f-b136-113771af36fa.png)

**Comment by ankush** [comment]
This is fixed in framework. Patch release pending.

**Comment by ankush** [comment]
@shariquerik

**Comment by muchai** [comment]
Referring to this? https://github.com/frappe/frappe/pull/15020
Doesn't fix the issue.

**Comment by muchai** [comment]
Resolved in latest update. Thank you.
