### ISSUE TITLE
pricing rule does not work on POS view v13.18.0 wrong calculation event trigger

### ISSUE THREAD

**Issue by andrewhartono** [frappe/erpnext#29282]
### Information about bug

pricing rule works normally on v13.17.0 but after upgrade to v13.18.0 it stop working.
all kind of pricing rule just do not work, even as simple as 10% disc of item barcode xyz.
it does not work on POS view, and it only work on form view after saving.
it appears that the triggers for pricing rule calculation only works after save, for POS view it can not appear at all normally so to work around it we must save as draft first then recall it again so that pricing rule calculation get triggered.

### Module

selling

### Version

ERPNext: v13.18.0 (HEAD)
Frappe Framework: v13.18.0 (HEAD)

### Installation method

FrappeCloud

**Comment by nemesis189** [comment]
@andrewhartono 
![pricingruleissue](https://user-images.githubusercontent.com/36098155/151319697-e1a61d60-9d62-4faf-8afd-b80d1ffd6e0c.gif)

A normal pricing rule is working fine on my instance, could you please more specific maybe with your example as to what's going wrong

**Comment by andrewhartono** [comment]
@nemesis189 
![min qty](https://user-images.githubusercontent.com/3880725/151497081-86930721-784b-47dc-9f0a-a662a8b8dcb9.jpg)

yes i have try your method, it's working if there is no min qty on pricing rule.
try it with min qty more than 1, maybe 2 or 4 then try again on POS, it will not work.
for example buy 2 to get 10% disc or buy 4 to get 30% disc

**Comment by andrewhartono** [comment]
> @andrewhartono ![pricingruleissue](https://user-images.githubusercontent.com/36098155/151319697-e1a61d60-9d62-4faf-8afd-b80d1ffd6e0c.gif)
> 
> A normal pricing rule is working fine on my instance, could you please more specific maybe with your example as to what's going wrong

@nemesis189 
![Pricing Rule](https://user-images.githubusercontent.com/3880725/151693965-978b8378-6088-4b71-b9df-b89f7711f5f1.gif)

you can see that after changing the pricing rule min qty, the POS somehow do not calculate item price although it show that there is 20% disc.
after we save it to draft and edit it back then we can get the correct item price and correct total invoice amount.
but in real production stage where there are many customer queuing it is slow and difficult for the user to keep saving as draft and edit it back.

**Comment by nemesis189** [comment]
this should fix it: https://github.com/frappe/erpnext/pull/29597

**Comment by andrewhartono** [comment]
@nemesis189 hi, i have update to ERPNext: v13.20.0 (HEAD) and Frappe Framework: v13.20.0 (HEAD) but the same problem still exist

**Comment by andrewhartono** [comment]
hi, i've updated to ERPNext: v13.21.0 (HEAD) and Frappe Framework: v13.21.0 (HEAD), the pricing rule problem is solved after checkout as it saves the transaction as draft but there is new problem, the payment method is gone... 
only the default payment method is available, it means only 1 option to pay, but if we use save as draft and edit it again then the other payment methods are available.
should i create a new issue for payment method problem and close this thread or stick with this thread?

**Comment by andrewhartono** [comment]
@nemesis189 Thank you the problem is now solved, so far pricing rule works normally.
