### ISSUE TITLE
Error when trying to login to knowledgebase

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3171]
This is the link location that is giving me the error message:
https://kb.erpnext.com/

This is the error I get when trying to login to the knowledgebase from the sitemap:

Server Error

Traceback (innermost last):
  File "/home/frappe/website-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.website.render.render(request.path)
  File "/home/frappe/website-bench/apps/frappe/frappe/website/render.py", line 38, in render
    data = render_page(path)
  File "/home/frappe/website-bench/apps/frappe/frappe/website/render.py", line 116, in render_page
    return build(path)
  File "/home/frappe/website-bench/apps/frappe/frappe/website/render.py", line 125, in build
    return build_method(path)
  File "/home/frappe/website-bench/apps/frappe/frappe/website/render.py", line 141, in build_page
    context = get_context(path)
  File "/home/frappe/website-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/home/frappe/website-bench/apps/frappe/frappe/website/context.py", line 73, in build_context
    ret = module.get_context(context)
  File "/home/frappe/website-bench/apps/frappe/frappe/templates/pages/list.py", line 23, in get_context
    context.update(get(**frappe.local.form_dict))
  File "/home/frappe/website-bench/apps/frappe/frappe/templates/pages/list.py", line 53, in get
    limit_start=limit_start, limit_page_length=limit_page_length)
  File "/home/frappe/website-bench/apps/frappe/frappe/templates/pages/list.py", line 103, in get_list
    limit_page_length = limit_page_length, ignore_permissions=ignore_permissions)
  File "/home/frappe/website-bench/apps/frappe/frappe/__init__.py", line 855, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/website-bench/apps/frappe/frappe/model/db_query.py", line 50, in execute
    return self.build_and_run()
  File "/home/frappe/website-bench/apps/frappe/frappe/model/db_query.py", line 53, in build_and_run
    args = self.prepare_args()
  File "/home/frappe/website-bench/apps/frappe/frappe/model/db_query.py", line 68, in prepare_args
    self.build_conditions()
  File "/home/frappe/website-bench/apps/frappe/frappe/model/db_query.py", line 196, in build_conditions
    match_conditions = self.build_match_conditions()
  File "/home/frappe/website-bench/apps/frappe/frappe/model/db_query.py", line 286, in build_match_conditions
    frappe.throw(_("No permission to read {0}").format(self.doctype))
  File "/home/frappe/website-bench/apps/frappe/frappe/__init__.py", line 248, in throw
    msgprint(msg, raise_exception=exc)
  File "/home/frappe/website-bench/apps/frappe/frappe/__init__.py", line 241, in msgprint
    _raise_exception()
  File "/home/frappe/website-bench/apps/frappe/frappe/__init__.py", line 226, in _raise_exception
    raise raise_exception, encode(msg)
 ValidationError: No permission to read Help Article

**Comment by anandpdoshi** [comment]
Fixed!

**Comment by fblauer** [comment]
The error is gone, but it won't let me comment. It says "login to comment"
which it lets me login only with google+, but then it keeps telling me to
login over and over again, and I still can't comment.

On Mon, Apr 27, 2015 at 3:26 PM, Anand Doshi <notifications@github.com>
wrote:

> Fixed!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3171#issuecomment-96787901>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by anandpdoshi** [comment]
Fixed. Can you refresh and try again?

**Comment by fblauer** [comment]
It works now. Thanks

On Mon, Apr 27, 2015 at 3:59 PM, Anand Doshi <notifications@github.com>
wrote:

> Fixed. Can you refresh and try again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3171#issuecomment-96797401>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555
