### ISSUE TITLE
Purchase Receipt and Stock Entry renamed to S13 Voucher and S11 respectively

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32159]
### Information about bug

![image](https://user-images.githubusercontent.com/1822868/189523791-8cabddd8-b1d1-4a52-a266-cfd795ec23fd.png)

### Module

stock

### Version

ERPNext: v14.0.3 (HEAD)
Frappe Framework: v14.5.0 (HEAD)

### Installation method

FrappeCloud

**Comment by muchai** [comment]
An update on this.
Seems far-fetched, but it happened. Someone Changed Label (via Custom Translation) of Purchase Receipt and Stock Entry in in one site, say **Site A**, but this label updates happened in another site **Site B**.

The person doing the label updates has no access, and doesn't know of **Site B**

**Comment by rohitwaghchaure** [comment]
It seems that you have made changes in the Public workspace directly therefore it's applying to all sites. Have you enabled developer mode?

**Comment by muchai** [comment]
Not sure if developer mode is enabled. Both of these sites are on FC, public benches.
Had reported this here, after the customer of site B raised the issue on Saturday, then when I realized what had happened, I reported it on FC.
It's resolved now, after update of the sites to the latest v14 releases.

**Comment by dj12djdjs** [comment]
> It's resolved now, after update of the sites to the latest v14 releases.

Closing as OP noted the issue was resolved by updating to latest version.

**Comment by muchai** [comment]
Still an issue.
See issue: https://frappecloud.com/support/tickets/232375 on FC.
This is either a deployment issue on FC, or a Frappe framework issue. Not sure.
