### ISSUE TITLE
Calendar showing dates wrongly

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3348]
For events or leave applications that spans across multiple days, it will not be reflected correctly in the calendar view. For example, 

Event spanning from 22 May to 25 May, the calendar view will only show it covers 22 May to 24 May. For example in the image attached, the event spans from 2 June 2015 to 6 June 2015, but the calendar only reflects up till 5 June 2015. It is also the same for leave applications calendar when it is showing the staff's leave. 

![image](https://cloud.githubusercontent.com/assets/12539216/7814241/71060f82-03f3-11e5-9f38-2132e7f94e9a.png)

**Comment by rmehta** [comment]
Does this happen in Chrome? This is related to other date issues, we have pushed a fix, maybe released today.

**Comment by justinlusg** [comment]
@rmehta this is still not fixed yet, i tried both chrome and IE and it has the same issue. Currently upgraded to 5.0.17. thanks!

**Comment by anandpdoshi** [comment]
@justinlusg in the above example, can you confirm the full values in the from and to values of the event, along with the time.

**Comment by justinlusg** [comment]
![image](https://cloud.githubusercontent.com/assets/12539216/7999623/f6f598c6-0b80-11e5-9937-be81e18c0efc.png)

@anandpdoshi  please see screenshot

**Comment by justinlusg** [comment]
Can this be fixed?

**Comment by justinlusg** [comment]
@anandpdoshi i realised this issue is the same for all other pages that uses the calendar (e.g. leave application, tasks, etc.) if there are multiple days, the calendar will reflect wrongly.

**Comment by anandpdoshi** [comment]
Hi. I am working on it. Issue is more problematic than expected. Should be done today.
