### ISSUE TITLE
ValidationError: Start Year and End Year are mandatory

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#36195]
### Information about bug

Happens on opening Accounting

### Module

accounts

### Version

ERPNext: v14.31.2 (HEAD)

Frappe Framework: v14.41.0 (HEAD)

Frappe HR: v14.6.2 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 801, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 801, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 533, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 501, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 450, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory
```

**Comment by Donferarri92** [comment]
Happening with me as well. It was'nt there in morning. I came here to create this bug report, but already there.

**Comment by bosue** [comment]
It would be a huge improvement if every validation error of the type „missing setting“ contained a link to the respective settings page where the problem may be fixed!

**Comment by deepeshgarg007** [comment]
@muchai This issue should be resolved now. Closing this issue

**Comment by bosue** [comment]
Still getting this issue on yesterday’s fresh install of ERPNext [e6abe1b](https://github.com/frappe/erpnext/commit/e6abe1b77f17f7c322b1904a48dbe358c8163720) on Frappe Framework [838599e](https://github.com/frappe/frappe/commit/838599e02bcb97c23d5bd927b410f4797d3b3689).

![IMG_1168](https://github.com/frappe/erpnext/assets/46800703/a74840c4-43c5-4931-aff3-07fde6090255)

**Comment by pankajjpatil** [comment]
What is solution for "Start Year and End Year are mandatory" & "Invalid expression set in filter fiscal_year"
Please guide.

ERPNext: v14.32.1 (version-14) Frappe Framework: v14.42.0 (version-14)

**Comment by FearsomePhobia** [comment]
Not sure if this is correlated but I've noticed that this error seems to have started occuring when setting the default fiscal year was removed and replaced with fetching the fiscal year from the current date.

The error still persists on every v14 release from when this issue was first posted. It's a fairly critical feature so I'm not sure how this hasn't been resolved yet.

This issue should probably be reopened.

**Comment by FearsomePhobia** [comment]
@deepeshgarg007 Unfortunately this issue is still persisting on every v14 release. If there is any tests or diagnostic steps I can perform to help get this resolved, please let me know.

**Comment by moayyaed** [comment]
> @muchai This issue should be resolved now. Closing this issue

as all mentioned the issue is still so how you close it with provide proper solution or provide any information 👎

**Comment by moayyaed** [comment]
@deepeshgarg007 

as all mentioned the issue is still so how you close it with provide proper solution or provide any information

**Comment by muchai** [comment]
@moayyaed
I'm on the below versions, and the error message is resolved.
ERPNext: v14.35.2 (HEAD)
Frappe Framework: v14.45.0 (HEAD)

**Comment by FearsomePhobia** [comment]
@muchai Unfortunately this error is still occurring on my instance using the same versions that you are using. If you have any information or resolution steps on how this has been resolved for your instance, please let us know.

**Comment by moayyaed** [comment]
> below

thank you for your response .
 I'm right now 
erpnext 14.33.2
frappe 14.43.1
hrms 14.10.1

so how I will upgrade.

anther thing happened with me in installation:
in initial setup wizard the abbreviation and logo not exists any more in brand page.


so could you please help?

**Comment by albadri92** [comment]
Hello all
It has been updated to

ERPNext: Version 14.35.2 (v14)

Frappe Frame: v14.45.0 (v14)

Frappe HR: v14.10.1 (v14)

But the problem still exists. The fiscal year cannot be specified in some reports. It must be manually challenged. In other cases, it is not possible. Even choosing the filter factor can not solve this problem, such as profit and loss chart and profit and loss report.
Is there any solution here

**Comment by FearsomePhobia** [comment]
Had some free time to find a solution, I think this is caused by a problem in the update process for some ERPNext instances.

Run `bench build` and check if the problem has been resolved (by viewing a report that initially had this error).
If that doesn't work, go to `erpnext/accounts/report/` and edit `financial_statements.py`.
In the `validate_dates` function, comment out these two lines as seen below (starting at line 129 as of writing):
```python
def validate_dates(from_date, to_date):
	#if not from_date or not to_date:
	#	frappe.throw(_("From Date and To Date are mandatory"))
```
Run `bench build` and once again check if the problem has been resolved.
At this point if this solution has worked, it should be safe to revert the commented lines back and run `bench build` again.

**Comment by shreyanshj** [comment]
For me Upgrading to ERPNext v14.36.0 and Frappe v14.46.0 and firing `bench build` did the trick. The financial reports are working now for me.
