### ISSUE TITLE
Rounded Total in Salary Slip showing with Global Setting off

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#3792]
Hi,

With the Disable Rounded Total setting in Global Settings enabled, the rounded totals are still showing in Salary Slips.

Will the rounded total be taken in on the payment vouvher, or the non-rounded amount?  If the latter, can I simply 'hide' the rounded total field on the DocType (using customise form)?

Thanks

Ardan

**Comment by ekpaxp** [comment]
To follow up, even with Disable Rounded Total enabled, the rounded amount is pushed to the Journal Voucher during the Payroll Process.

**Comment by rmehta** [comment]
Fixed.

**Comment by weenee** [comment]
@rmehta The rounded amount is still getting pushed to the Journal Voucher during Payroll Processing. Kindly assist on this issue. Thank you.

**Comment by weenee** [comment]
@rmehta has this issue been resolved? Please advice. Thanks.
