### ISSUE TITLE
[V7] Chart of Accounts

### ISSUE THREAD

**Issue by Gleisson03** [frappe/erpnext#5642]
Problems in the Chart of Accounts:
• Desk Tree -> Can not see any account listed.

• Desk List -> You can see the list of accounts, but when we click on any, the following error appears:
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 33, in GetDoc
    run_onload (doc)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 199, in run_onload
    doc.run_method ( "onload")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 603, in run_method
    return Document.hook (fn) (self, * args, ** kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 768, in composer
    return composed (self, method, * args, ** kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 751, in runner
    add_to_return_value (self, fn (self, * args, ** kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 597, in
    fn = lambda self, * args, ** kwargs: getattr (self, method) (* args, ** kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/account.py", line 19, in onload
    self.get ( "__ onload"). can_freeze_account = True
AttributeError 'dict' object has no attribute 'can_freeze_account'
```

**Comment by saurabh6790** [comment]
@Gleisson03 Fixed by @rmehta please pull latest updates for frappe and erpnext.

**Comment by Gleisson03** [comment]
I'm still a problem, I can not see the Accounts list in the Chart of Accounts.
This problem is only when I use the language "Portuguese-Brazil," if I change the language to "English" appears normally.
![screenshot 2016-07-06 00 21 05](https://cloud.githubusercontent.com/assets/13992475/16606629/df5b8da2-430f-11e6-8e2f-0005d57c5b11.jpg)

I would like to thank very much your work, I love the ERP Next.

**Comment by rmehta** [comment]
@Gleisson03 can you start a new issue for this?

> I would like to thank very much your work, I love the ERP Next.

Thanks for reporting issues!

**Comment by Gleisson03** [comment]
Of course I can. To both, thank you for your attention.
