### ISSUE TITLE
Refresh function not working in v7

### ISSUE THREAD

**Issue by srinivasragav** [frappe/erpnext#5726]
Hi All,
The below script works perfectly in v6.23 but wherever I try to use the `"refresh function"` in v7 I am getting this error in the console . `Uncaught TypeError: Cannot read property 'get_field' of undefined`
```
frappe.ui.form.on("Sales Order", "refresh", function (frm, cdt, cdn) {
    frm.set_query("item_code", "items", function () {
         return{
		filters: {
			"company": frm.doc.company
		}
         }
    });
});
```
Not only here , many of the scripts having refresh does not work in v7 . Please help

Thanks in advance

**Comment by anandpdoshi** [comment]
Use ‘Sales Order Item’ instead of ‘Sales Order’. That should fix it.

**Comment by srinivasragav** [comment]
@anandpdoshi . Many thanks for responding in spite of your hectic schedule sir , I did that but no change , still the same error , wherever the refresh function is used I am getting the same error. Thank you

**Comment by nabinhait** [comment]
Try to define set_query function inside "onload" function.

**Comment by srinivasragav** [comment]
Thanks for responding sir @nabinhait . I am a novice , could you please guide me how to do that ?

**Comment by rmehta** [comment]
@srinivasragav its best you pay a freelancer to help you then.

**Comment by srinivasragav** [comment]
@rmehta . But no issues with v6.23 the same script works like a charm , so the issue is with the version . I could get the things done by a freelancer but what about the bug in the software sir ?

**Comment by rmehta** [comment]
@srinivasragav for this, the issue is in your asking for help from developers for your customization without offering to pay. The software is free, someone's time is not. 

Please follow these basic rules for participating in any open source community. Search online, read documentation and then ask for help. You are saving your time and wasting other's by not doing enough research.
