### ISSUE TITLE
Email Account Structure Not Compatble with Office365

### ISSUE THREAD

**Issue by imllc** [frappe/erpnext#6602]
After a month of testing we have determined several major issues with how the email accounts are structured for sending and receiving.
1 it is a limitation for anonymous accounts that you have to have a ERPNext password in the configuration for an anonymous relay account.  the existence of the password cause authentication failure when office 365 connector requires no password.
2 the utilization of only one outbound account doesn't allow the flexibility of branding for uses like support and billing.  incoming and outgoing mail could be cataloged based on sending and receiving account. This also causes authentication errors when ERPNext send as, regardless of giving send as rights in office365.  this syntax incompatibility also cause failure. 
3In addition verified sending accounts randomly fail to stay verified so imap pulls fail simply re-verify works but is unreliable for something like support desk.

Below are the transaction tests to verify the problems in addition this was confirmed by Microsoft.
https://discuss.erpnext.com/t/office-365-mail/15981?u=imllc
https://discuss.erpnext.com/t/email-is-a-problem/16571?u=imllc

**Comment by milindnaphade** [comment]
I struggled with the similar issue for a whole day. I guess there's an easy way to handle it.

Here's what I did.

1. Erpnext installation script also installed postfix.
2. Without modifying anything on postfix I added the ERP server IP to a receive connector on O365 for allowing inbound emails to O365.
3. The SMTP server in ERP has a setting set to localhost with port 25.
4. Notification email address was modified to match my domain name.

I think you just need to let postfix determine the MX record itself while you still allow SMTP relay on your O365 tenant.

Inbound emails can always be synced using IMAP. I am sure you have done that. 

I still agree that the documentation needs to be clearer. Can work with the contributors to improvise it. Just don't know how and where to start.

**Comment by nostahl** [comment]
this issue is still open, is office 365 still an issue with ERPNext??

**Comment by parsimonyERP** [comment]
Our experiences with Office365 closely followed this discussion: (we were getting random equals "=" signs in emails that we sent out.) [https://discuss.erpnext.com/t/random-characters-added-to-emails/51675]

**Comment by nostahl** [comment]
We have not setup this postfix portion but just simply trying to use office 365 with ERPNext results in emails coming through with no body for us.

**Comment by kennethsequeira** [comment]
@parsimonyERP I believe the "=" showing up was solved with this PR and other related fixes: https://github.com/frappe/frappe/pull/8912

**Comment by kkulloters** [comment]
I'm still having an error in using outlook microsoft 365 for my outgoing email it gives me an error "Invalid email and password"
