### ISSUE TITLE
[BUGS] - Latest version has critical bugs in HRM Module

### ISSUE THREAD

**Issue by saurabhvashist** [frappe/erpnext#6834]
There are three encountered bugs in the HRM Module.

First

    The Salary slip created for employees is not picking the links like designation, branch & department. Even though these are specifically mentioned in the Salary Slip Format (Print Format) yet these links are not being picked by the system

Second

    The system is not creating Salary Slip for one of the employee. This is generally the last employee amongst the whole list of employees. I have checked every setting in the system and everything is fine with the last employee but it doesn't work from Process Payroll.

    If we add another employee then the last employee becomes second last employee and his salary slip is created but again the newly added (last) employee is missed out.

Third

    The default behavior for creating new employee has been changed in the latest version i.e. v7.1. The default employee number is EMP/00001 but when I create first employee in a fresh installation, it comes out as EMP/0001. And with the addition of second employee the series gets updated to default strong length and second employee is created as EMP/00002.

    Though we can change this behavior by changing the Data default from the Naming Series by updating the series as EMP/.#### this will ensure that all employee are created in similar pattern however default behavior of the system should by default create records which are in sync with other.

Early resolution would be highly appreciated..

--
Regards
Saurabh

**Comment by KanchanChauhan** [comment]
@saurabhvashist 
**Issue 1:** Resolved via https://github.com/frappe/erpnext/pull/6835. Will be merged soon.
**Issue 2:** Could not replicate it, tested for 5 employees, it worked fine. Below are screenshots.
<img width="909" alt="screen shot 2016-11-06 at 12 42 06 pm" src="https://cloud.githubusercontent.com/assets/16913064/20035944/88b9705c-a41e-11e6-93b0-f73543394486.png">
<img width="298" alt="screen shot 2016-11-06 at 12 42 18 pm" src="https://cloud.githubusercontent.com/assets/16913064/20035945/8c88c19c-a41e-11e6-8ebd-218d9aa5961e.png">
**Issue 3:** Unfortunately could not replicate this even either, tried on fresh install. Naming pattern seems to be in sync. See screenshot below.
<img width="720" alt="screen shot 2016-11-06 at 12 55 43 pm" src="https://cloud.githubusercontent.com/assets/16913064/20036018/7146bac2-a420-11e6-923b-dfdaf7a43f95.png">

**Comment by saurabhvashist** [comment]
The problems persists on my server...


**Issue 2:**
I created a test employee named New Employee but Process Payroll option didn't created Salary slip for New Employee. You can see only three salary slips are created whereas we have four employee on the system.
![6](https://cloud.githubusercontent.com/assets/22211942/20038784/61b061fa-a45f-11e6-8c47-7521e128ce37.png)


**Issue 3:**
Newly created employee shows the Employee Naming series with EMP/00004 whereas last created employees was at EMP/0003. So there is clearly something that went wrong during update from older version, as far as Employee Naming series is concerned. As mentioned earlier, this can be controlled by explicitly mentioning Employee Naming Series as EMP/.#### yet, the old series for existing installations should not break with new versions updates.
![3](https://cloud.githubusercontent.com/assets/22211942/20038789/6e4034ae-a45f-11e6-8fa1-2073dd744662.png)


Additionally, I want to highlight few more bugs:


**Issue 1: (few more insights)**
In my case, the user Saurabh Vashist is Managing Partner and user Ranjan Jha is Area Sales Manager. When I try to create a new salary slip it shows details for Saurabh Vashist along with Branch, Department & Designation. But when I change employee from the same page, these three links namely, Branch, Department & Designation are not picked automatically. Even worst is that it leaves the already picked up links as it is, making user Ranjan Kumar as Managing Partner of the company. See screen-shots:
![5](https://cloud.githubusercontent.com/assets/22211942/20038838/421df892-a460-11e6-9479-371b28d3bccf.png)
![1](https://cloud.githubusercontent.com/assets/22211942/20038839/47b68a8a-a460-11e6-85e0-e5e537271d12.png)
![2](https://cloud.githubusercontent.com/assets/22211942/20038840/4b940704-a460-11e6-9e69-ef2b70ac7756.png)

**Issue 5:**
New version of the ERP does not have a default naming series for Salary Structure. This forces the user to name the Salary Structure by himself. Default behavior of the older version to give a default name was good for those users who are new. Those experienced can always change the way Salary Structure Naming Series is shown & saved in the system.
![4](https://cloud.githubusercontent.com/assets/22211942/20038900/4fcbfe84-a461-11e6-9b10-efed0b429045.png)

**Comment by KanchanChauhan** [comment]
Can you please raise separate issue for each issue. It gets difficult to address all the issues in one issue. Hope you understand.

**Comment by saurabhvashist** [comment]
Hi @KanchanChauhan 

I updated the server today but it didn't solved my issue. I'm still facing Issue 1.

I customized the Salary Slip form and made it mandatory to have Branch, Department & Designation on the salary slip. In in the present scenario, when I try to save the new salary slip, it throws an error. See screen-shot:
![salary-slip](https://cloud.githubusercontent.com/assets/22211942/20056553/dbfe3966-a50c-11e6-8af1-9a21a9161c33.png)

**Comment by KanchanChauhan** [comment]
The PR was merged few seconds ago, you might have to update again.

**Comment by saurabhvashist** [comment]
It is still not working for me. I checked out your Beta Server and took this screen shot:
![1](https://cloud.githubusercontent.com/assets/22211942/20061272/35b7b9b0-a525-11e6-8159-729abe183a03.png)

When I went to change Branch, Department & Designation, I was not able to change it as a Demo User. 

Do you suggest to hire an ERPNext professional to look into my system or should I wait till you double check the error?

**Comment by KanchanChauhan** [comment]
Sorry about it, looks like beta is not updated. Will let you know as soon as it is done. You can start testing after that.

**Comment by saurabhvashist** [comment]
Thanks. Working on my server now!

**Comment by KanchanChauhan** [comment]
Let us know if you can replicate other issues so that we can close this thread.

**Comment by saurabhvashist** [comment]
Issue 2: Process Payroll: 
Has been created separately #6870 

Issue 3: Employee Series: 
It seems the change in default behavior of employee numbering series from EMP/.#### to EMP/.##### is being enforced on systems which have not defined the Employee series in their system. Once we define it in Setup Naming Series, the issue has no room to surface as it follows the explicitly numbered series. However, the update should have respected the on-going series and should have continued to follow the old series i.e. EMP/.#### in place of generating new series with EMP/.#####. I don't know if this can be resolved for installations where the Admin has not setup the employee numbering series explicitly and has left it to default behavior.
