### ISSUE TITLE
reset-perms remove all permission even Administrator

### ISSUE THREAD

**Issue by ccfiel** [frappe/erpnext#7567]
I tried 

> bench --site all reset-perms

after issuing the command no error display but after that all permission is gone even administrator has no permissions.

Note:
My code is branch master and before Issue reset-perms. I did bench update to make sure that my repo is updated.

**Comment by ccfiel** [comment]
I have notice the code in reset-perms its just deleting all records in tabDocPerm that is istable=0 and custom=0.
Would that be the reason that even Administrator has no access because DocPerm is empty?


``` 
def reset_perms(doctype):
	"""Reset permissions for given doctype."""
	from frappe.desk.notifications import delete_notification_count_for
	delete_notification_count_for(doctype)

	frappe.db.sql("""delete from tabDocPerm where parent=%s""", doctype)
	frappe.reload_doc(frappe.db.get_value("DocType", doctype, "module"),
		"DocType", doctype, force=True)
```

**Comment by rmehta** [comment]
This should be fixed with `Custom Perm` in develop 😄 

In master, this should be fixed, because `force` no longer updates permissions. I think there is a new parameter 

CC @nabinhait

**Comment by chdecultot** [comment]
Hi @rmehta, @ccfiel,

For information I experienced it this morning on an up-to-date ERPNext instance and it is unfortunately not fixed yet.

`bench --site all reset-perms` still deletes all permissions even for the administrator.

I did a backup restore but was there any other option to reset the permissions ?

Thanks a lot!

**Comment by umairsy** [comment]
https://github.com/frappe/erpnext/issues/7697

**Comment by chdecultot** [comment]
Thanks @umairsy
