### ISSUE TITLE
Issue on creating payment entry from SINV on letter head

### ISSUE THREAD

**Issue by thekingofboys** [frappe/erpnext#7917]
when creating payment entry base on Sales invoice, its not feching the letter head set on Invoice, its taking the last letter head set as default. when you have more than one letter head or companies

**Comment by nabinhait** [comment]
fixed

**Comment by thekingofboys** [comment]
did you upload to the last version, because its still not working
