### ISSUE TITLE
Amount field in POS should be read only

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8621]
Hi,

The Amount field in the V8 POS should be read only. Some users inadvertently put the price of an item in the amount field and then proceed to payment screen and wonder why the figure isn't showing automatically in the mode of payment. Some even fill the mode of payment manually and submit the invoice! This leads to zero value invoices with status showing as 'Overdue'

Kind regards,

**Comment by vrms** [comment]
shouldn't the **Price** field be r/o as well?

**Comment by Olawale1** [comment]
Hi @vrms 

Status of price field should depend on permission of the user as defined in the POS Profile. If 'Allow User to Edit Rate' field is not checked then the field should be read only. If it is checked then the field should be editable

Thanks

Kind regards,

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing great. Has this fix been pushed? I just updated to the latest version and the issue is still there!

Thanks

**Comment by tundebabzy** [comment]
Hello @Olawale1 
The fix has now been merged

**Comment by Olawale1** [comment]
Hi @tundebabzy

Thanks for the update 

Cheers!

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure @tundebabzy 

The issue is still not totally fixed. The Amount field is still editable! It should be a read-only field which is auto-calculated based on price and quantity

Please help fix

Thanks

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing great. Any update on this? As long as the Amount field is editable, users can make the error of editing price there (even though it ultimately has no effect). It'll be much more tidy to make it read-only just like the Price List Rate field

Thanks

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing great. Just a kind reminder. Please let me know if I should open this issue afresh

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

The issue is fixed(see attachment), also kindly check allow user to edit rate is disabled in the POS profile

![screen shot 2017-07-19 at 4 58 31 pm](https://user-images.githubusercontent.com/8780500/28364809-c091f8ca-6ca3-11e7-8fe1-e9a451e8ef3d.png)

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Thanks for responding. It's not fixed yet! Please find screenshot below. Amount field should be 'Read Only' regardless of whether user is able to edit rate or not

![pos amount field issue](https://user-images.githubusercontent.com/9269337/28367570-55def7ae-6c89-11e7-83fb-bb51b8362767.png)

Kind regards,

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing great. Can you please confirm you've identified this issue?

Thanks

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing well. This issue is still pending as shown in the screenshot above. Please give update on status and/or re-open

Thanks
