### ISSUE TITLE
Duplicated buttons on production order

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#9676]
Hello,

After updating to version 8.3 I,ve got the buttons on the screenshot below duplicated, and the buttons are not working

<img width="975" alt="screen shot 2017-07-06 at 1 31 19 pm" src="https://user-images.githubusercontent.com/18335894/27921933-bfd14bb0-624f-11e7-8ac4-3ca5ee82c4e8.png">

**Comment by nabinhait** [comment]
Fixed in the latest release

**Comment by applepipe** [comment]
hello @nabinhait the button is still not functional

this is the error on console

<img width="1668" alt="screen shot 2017-07-06 at 5 13 47 pm" src="https://user-images.githubusercontent.com/18335894/27930876-8fcfabae-626e-11e7-8490-b125648ef621.png">

**Comment by oschauf** [comment]
Same problem here

**Comment by nabinhait** [comment]
Please check after updating latest release 8.3.2
